### ISSUE TITLE
Software closes immediately

### ISSUE THREAD

**Issue by sohrabsarabian** [Cardiac-MR-Group-Lund/segment-open#9] opened 2020-04-22 01:12 UTC
### Steps to reproduce
I open the software (stand-alone version)
### Expected behavior
then it closely immediately after opening on windows 10.
### Details
Version/commit: 
Link to data set used:

**Comment by johannestoger** [comment] 2020-06-02 13:24
Hi, my apologies for not responding to this earlier.

So as I understand, you have downloaded the source from the Github version, and then you are starting it from Matlab, is that correct? And then it fails to start?

Can you send a screenshot or copy-paste the output in the Matlab window?

If the problem is for a specific set of DICOM files, it would really help if you could send the DICOMs anonymized so I can test.

**Comment by lriazy** [comment] 2020-11-19 12:25
I have the same issue on the stand-alone version on windows 10.  There is an error about "dispexception" undefined fpr "MException" and then it closes.

**Comment by johannestoger** [comment] 2020-11-19 12:49
Please also provide your Matlab version. Only **R2014a** is supported for segment-open at this time, newer will not work.

**Comment by lriazy** [comment] 2020-11-19 13:19
The stand-alone version automatically installs a Matlab Compiler from 2019, I believe. Installing the Compiler from 2014 did not work.

**Comment by johannestoger** [comment] 2020-11-19 15:42
Well, the stand-alone method installs a "Matlab Compiler Runtime", but this is not connected to the Matlab version you use to run segment-open.

**Comment by johannestoger** [comment] 2020-11-20 15:57
@sohrabsarabian I'm closing this for now since you have not replied since June. You are welcome to re-open if you wish.

**Closed by johannestoger** 2020-11-20 15:57 UTC
